djangolevel5/learning_users/basic_app/urls.py
from django.urls import re_path
from basic_app import views
from django.urls import path, re_path, include
from basic_app import views
from basic_app import urls


#template URLs
app_name = 'basic_app'

urlpatterns=[
    re_path(r'^register/$',views.register,name='register'),
    re_path(r'^user_login/$',views.user_login,name='user_login'),
    re_path(r'^$',views.index,name='index'),
]

djangolevel5/learning_users/learning_users/urls.py
from django.contrib import admin
from django.conf.urls import url
from django.urls import re_path, include
from basic_app import views
from basic_app import urls

urlpatterns = [
    re_path(r'^$',views.index,name='index'),
    #re_path(r'^special/',views.special,name='special'),
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^basic_app/',include('basic_app.urls')),
    re_path(r'^logout/$', views.user_logout, name='logout'),
]

djangolevel5/learning_users/basic_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class UserProfInfo(models.Model):
     user = models.OneToOneField(User, on_delete=None)

     #additional classes
     portfolio_site = models.URLField(blank= True)
     profile_pic = models.ImageField(upload_to='profile_pics',blank=True)

     def __str__(self):
         return self.user.username

djangolevel5/learning_users/basic_app/forms.py
from django.forms import ModelForm
from django import forms
from basic_app.models import UserProfInfo
from django.contrib.auth.models import User


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username','email','password')


#class UserProfInfoform(forms.ModelForm):
class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfInfo
        fields = ('portfolio_site','profile_pic')

djangolevel5/learning_users/basic_app/views.py
from django.shortcuts import render
from django.urls import path, re_path
from basic_app.forms import UserForm,UserProfileInfoForm
from django.contrib.auth.models import User
from django.urls import reverse
from django.urls import resolve
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth import login,logout, authenticate

# Create your views here.
#Index view

def index(request):
    return render(request,"basic_app/index.html")

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

def register(request):
    registered = False
    if request.method == "POST":
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data = request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                print('found it')
                # If yes, then grab it from the POST form reply
                profile.profile_pic = request.FILES['profile_pic']

            # Now save model
            profile.save()
            registered = True
        else:
            print(user_form.errors,profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()


    return render(request,"basic_app/registration.html",context={'user_form':user_form,
    'profile_form' : profile_form,
    'registered': registered})




def user_login(request):

    if request.method == 'POST':
        # First get the username and password supplied
        username = request.POST.get('username')
        password = request.POST.get('password')

        # Django's built-in authentication function:
        user = authenticate(username=username, password=password)

        # If we have a user
        if user:
            #Check it the account is active
            if user.is_active:
                # Log the user in.
                login(request,user)
                # Send the user back to some page.
                # In this case their homepage.
                return render(request,'basic_app/index.html',{})
            else:
                # If account is not active:
                return HttpResponse("Your account is not active.")
        else:
            print("Someone tried to login and failed.")
            print("They used username: {} and password: {}".format(username,password))
            return HttpResponse("Invalid login details supplied.")

    else:
        #Nothing has been provided for username or password.
        return render(request, 'basic_app/login.html', {})

djangolevel5/learning_users/templates/basic_app/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
  </head>
  <body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
<div class="container">
    <ul class="navbar-nav">
      <li><a class="navbar-brand" href="{%url 'index' %}">Home</a></li>
      <li class="nav-item"><a class="nav-link" href="{%url 'admin:index' %}">Admin</a></li>
      <li class="nav-item"><a class="nav-link" href="{%url 'basic_app:register' %}">Register</a></li>

     {%if user.is_authenticated %}
    <li class="nav-item"><a class="nav-link" href="{% url 'logout' %}">LogOut</a></li>
     {% else %}
     <li class="nav-item"><a class="nav-link" href="{% url 'basic_app:user_login' %}">Log In</a></li>
     {% endif %}

  </ul>
  </div>
</nav>
<div class="container">
  {%block body_block%}
  {%endblock%}
</div>

  </body>
</html>

djangolevel5/learning_users/templates/basic_app/index.html
<!DOCTYPE html>
{%extends "basic_app/base.html" %}

{%block body_block%}
<div class="jumbotron">
<h1>Welcome to the homepage</h1>
</div>
{%endblock%}

djangolevel5/learning_users/templates/basic_app/login.html
{%extends 'basic_app/base.html'%}
{%block body_block%}
<form class="{% url 'basic_app:user_login' %}" action="index.html" method="post">
  {% csrf_token %}
  <label for="username">Username: </label>
  <input type="text" name="username" value="">

  <label for="password">Password:</label>
  <input type="password" name="password">

  <input type="submit" name="" value="Login">
</form>
{% endblock %}

djangolevel5/learning_users/templates/basic_app/registration.html
<!DOCTYPE html>
{%extends "basic_app/base.html" %}
{%load staticfiles %}


{%block body_block%}
<div class="jumbotron">
  {% if registered %}
  <h1>Thank you for registering</h1>
  {% else %}
  <h1>Register Here!</h1>
  <h3>Fill out the registration for below</h3>

  <form enctype="multipart/form-data" method="post">
    {%csrf_token%}
    {{user_form.as_p}}
    {{profile_form.as_p}}
    <input type="submit" name="" value="Submit">
  </form>
  {% endif %}

</div>

{%endblock%}